data:
  # Where to save the demos
  save_path: datasets/colosseum_data/
  # The size of the images to save
  image_size: [1280, 720]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 100
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: False
    point_cloud: False
  # The cameras that we will be enabled
  cameras:
    left_shoulder: False
    right_shoulder: False
    overhead: False
    wrist: True
    front: False
  # Store depth as 0 - 1
  depth_in_meters: True
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
env:
  task_name: "put_money_in_safe"
  seed: 42
  scene:
    factors:

      - variation: object_color
        name: manip_obj_color
        enabled: True
        targets: [dollar_stack, dollar_back_visual, dollar_front_visual]
        color_same: True
        seed: ${env.seed}

      - variation: object_color
        name: recv_obj_color
        enabled: True
        targets: [safe_door, safe_body]
        color_same: True
        seed: ${env.seed}

      - variation: object_texture
        name: manip_obj_tex
        enabled: True
        targets: [dollar_back_visual, dollar_front_visual, dollar_stack]
        uv_scale: [0.25, 0.25]
        seed: ${env.seed}

      - variation: object_texture
        name: recv_obj_tex
        enabled: True
        targets: [safe_body, safe_door]
        seed: ${env.seed}

      - variation: object_size
        name: manip_obj_size
        enabled: True
        targets: [dollar_stack, dollar_back_visual, dollar_front_visual]
        scale_range: [0.5, 1.0]
        scale_same: True
        seed: ${env.seed}

      - variation: light_color
        enabled: True
        targets: [DefaultLightA, DefaultLightB, DefaultLightD]
        color_range: [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]]
        seed: ${env.seed}

      - variation: table_texture
        enabled: True
        seed: ${env.seed}

      - variation: table_color
        enabled: True
        color_range: [[0.25, 0.25, 0.25], [1.0, 1.0, 1.0]]
        seed: ${env.seed}

      - variation: background_texture
        enabled: True
        seed: ${env.seed}

      - variation: distractor_object
        enabled: True
        targets: [spawn_boundary0]
        num_objects: 8
        seed: ${env.seed}

      - variation: camera_pose
        enabled: True
        targets: [cam_wrist]
        euler_range: [[-0.05, -0.05, -0.05], [0.05, 0.05, 0.05]]
        position_range: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.3]]
        seed: ${env.seed}
