data:
  # Where to save the demos
  save_path: datasets/colosseum_data/
  # The size of the images to save
  image_size: [640, 480]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 10
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: False
    point_cloud: False
  # The cameras that we will be enabled
  cameras:
    left_shoulder: False
    right_shoulder: False
    overhead: False
    wrist: True
    front: False
  # Store depth as 0 - 1
  depth_in_meters: True
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
env:
  task_name: "slide_block_to_target"
  seed: 42
  scene:
    factors:

      - variation: object_color
        name: manip_obj_color
        enabled: True
        targets: [block]
        seed: ${env.seed}

      - variation: object_texture
        name: manip_obj_tex
        enabled: True
        targets: [block]
        seed: ${env.seed}

      # - variation: object_size
      #   name: manip_obj_size
      #   enabled: True
      #   targets: [block]
      #   scale_range: [0.75, 1.25]
      #   seed: ${env.seed}

      - variation: light_color
        enabled: True
        targets: [DefaultLightA, DefaultLightB, DefaultLightD]
        color_range: [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]]
        seed: ${env.seed}

      - variation: table_texture
        enabled: True
        seed: ${env.seed}

      - variation: table_color
        enabled: True
        color_range: [[0.25, 0.25, 0.25], [1.0, 1.0, 1.0]]
        seed: ${env.seed}

      - variation: background_texture
        enabled: True
        seed: ${env.seed}

      - variation: distractor_object
        enabled: True
        targets: [spawn_boundary0]
        num_objects: 5
        seed: ${env.seed}

      - variation: camera_pose
        enabled: False
        targets: [cam_front,
                  cam_over_shoulder_left,
                  cam_over_shoulder_right]
        euler_range: [[-0.05, -0.05, -0.05], [0.05, 0.05, 0.05]]
        position_range: [[-0.1, -0.1, -0.1], [0.1, 0.1, 0.1]]
        seed: ${env.seed}

      - variation: object_friction
        enabled: True
        targets: [block]
        friction_range: [0.75, 1.0]
        friction_same: True
        seed: ${env.seed}

      - variation: object_mass
        enabled: True
        targets: [block]
        mass_range: [1.0, 15.0]
        seed: ${env.seed}
